AWSTemplateFormatVersion: '2010-09-09'
Description: IAM Role 

Resources:
  MyIAMRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: s3policy
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: s3policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:ListBucket
                  - s3:GetObject
                  - s3:PutObject
                  - ec2:Describe*
                Resource: "*"
